In [1]:
import numpy as np

In [2]:
def RC4_K(key, n=256):
  S = np.array(range(n), dtype=int)
  j = 0
  for i in range(n):
    j = (j + S[i] + key[i % len(key)]) % n
    S[i], S[j] = S[j], S[i]
  return S

In [3]:
def RC4_PRGA(length, S, n=256):
  key_stream = np.zeros(length, dtype=int)
  i = 0
  j = 0
  for k in range(length):
    i = (i + 1) % n
    j = (j + S[i]) % n
    S[i], S[j] = S[j], S[i]
    key_stream[k] = S[(S[i] + S[j]) % n]
  return key_stream

In [4]:
RC4_K([1, 1, 3])

array([  1,  33, 153,   9, 168,  17, 135, 171,  21,  47,  35,  67,  85,
        40,  83, 122, 105, 142, 195,  23, 204, 110, 173,  68,  96,  52,
        61,  89, 118,  53,  19, 244,  50,   2,  36, 176, 166, 147,  73,
       228, 194,  71, 243,  87, 156,  79,  22, 255,  29,  98, 151, 102,
       214,  51, 225, 148, 199,  55,  59, 115, 119, 126,  76, 116, 184,
       132,  56,  72,  82, 152,  65,  57, 150, 127, 121,  41, 235,  93,
       221, 202, 108, 210,  75,   8, 113,  91, 141,  60,  30, 217, 206,
       170,  15, 125, 172, 219, 234, 209,  34, 193,  42,  20,   6,  16,
        69, 112, 117, 227, 128,  54, 120,  28, 175, 164,  66, 252, 178,
       233, 107,  49, 250, 197, 239, 216, 253, 254, 129, 188, 165, 251,
       182, 218,   7, 101, 124,   4, 203, 232, 123,  77,  18,  58, 155,
        46, 163, 231, 177, 162, 140, 207, 237, 223,  24,   5, 157,  32,
        90, 149,  39, 139, 145, 169, 236, 134, 212,  86,  27, 144, 131,
       174, 180, 103, 136, 249, 192, 158,  74, 196,   3, 246, 16

In [5]:
RC4_PRGA(1000, RC4_K([1, 1, 3]))

array([176,  12,  22,  77,  83, 136, 168,  19,  54, 231, 209, 221, 194,
        35,   6,   4, 162,  44, 252, 184, 152, 142, 235, 141, 184,  26,
        60,  14, 203, 124, 118, 135,  95, 204, 126, 230,  94, 149, 197,
        50,  68, 161, 246,  62, 109, 184, 148,  37, 241, 173, 136, 123,
       141, 247, 230, 194, 134, 203,  77, 142, 133, 120,  70, 173,  25,
        75, 244,  64, 117,  47, 147,  38,  98, 148, 217, 182, 222, 236,
       224,  51,  32, 210, 189, 249, 105,  56, 180,  89,  11, 212, 135,
        55, 178, 100, 151, 116,  21, 144,  16,  76, 222, 224, 166,  90,
        22,  56, 181,  97, 155, 109, 109, 179, 231,  45, 142,  89, 143,
        49,  69,  96, 116,  32, 248, 200, 123, 212, 255,  98,  72, 134,
       149,  79, 146, 117, 181, 247,  44, 158, 227, 115, 114, 154, 222,
        10,  86,   7, 161, 233, 107, 228, 241, 232, 145,  18, 117, 212,
        81, 152,  14, 148,  71, 227,  53, 116,  29,   2,   0, 218, 148,
        41, 192,  35,  48,  32,  69, 138, 255, 145,  35,  45, 23

In [7]:
RC4_K([1, 2, 1], 4)

array([1, 3, 2, 0])